# Add 
# JWT_SECRET - used by auth-service, user-service
# GOOGLE_API_KEY - used by ai agent (gemini)
# LLM_MODEL - gemini model for the agent-service
apiVersion: v1
kind: Secret
metadata:
  name: fitforge-app-secrets
  namespace: fitforge
  labels:
    app.kubernetes.io/part-of: fitforge
type: Opaque
stringData:
  JWT_SECRET: "this-is-my-jwt-secret"
  GOOGLE_API_KEY: "CHANGE-ME-your-google-ai-api-k"
  LLM_MODEL: "gemini-2.5-flash-lite"