apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: fitforge
  labels:
    app.kubernetes.io/part-of: fitforge
    app.kubernetes.io/component: database
type: Opaque
stringData:
  mongodb-root-password: "RootPass@123"
  mongodb-passwords: "AuthPass@3,UserPass@3,WorkPass@3,NutriPass@3,ProgPass@3"
  mongodb-metrics-password: "RootPass@123"
  mongodb-replica-set-key: "RootPass@123"