apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: fitforge
  labels:
    app.kubernetes.io/part-of: fitforge
    app.kubernetes.io/component: database
type: Opaque
data:
  mongodb-root-password: Um9vdFBhc3MxMjM=
  mongodb-passwords: QXV0aFBhc3MxMjMsVXNlclBhc3MxMjMsV29ya1Bhc3MxMjMsTnV0cmlQYXNzMTIzLFByb2dQYXNzMTIz
  mongodb-metrics-password: Um9vdFBhc3MxMjM=
  mongodb-replica-set-key: Um9vdFBhc3MxMjM=