apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: fitforge
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: fitforge
data:
  PORT: "5001"
  MONGO_URI: "mongodb://auth_user:AuthPass123@mongodb-headless.fitforge.svc.cluster.local:27017/auth_db?replicaSet=rs0&authSource=auth_db"