# Service port 80 => nginx controller port 3000
# Access via: http://<NODE_IP>:<NODE_PORT>
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: fitforge
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: fitforge
    app.kubernetes.io/component: frontend
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30080