apiVersion: v1
kind: ConfigMap
metadata:
  name: workout-service-config
  namespace: fitforge
  labels:
    app.kubernetes.io/name: workout-service
    app.kubernetes.io/part-of: fitforge
data:
  PORT: "5003"
  MONGO_URI: "mongodb://workout_user:WorkPass123@mongodb-headless.fitforge.svc.cluster.local:27017/workout_db?replicaSet=rs0&authSource=workout_db"