# ─────────────────────────────────────────────────────────────────────────────
# FitForge — workout-service ConfigMap
# ─────────────────────────────────────────────────────────────────────────────
apiVersion: v1
kind: ConfigMap
metadata:
  name: workout-service-config
  namespace: fitforge
  labels:
    app.kubernetes.io/name: workout-service
    app.kubernetes.io/part-of: fitforge
data:
  PORT: "5003"
  MONGO_URI: "mongodb://mongo-0.mongo-headless.fitforge.svc.cluster.local:27017,mongo-1.mongo-headless.fitforge.svc.cluster.local:27017,mongo-2.mongo-headless.fitforge.svc.cluster.local:27017/workout_db?replicaSet=rs0"
