apiVersion: v1
kind: Service
metadata:
  name: workout-service
  namespace: fitforge
  labels:
    app.kubernetes.io/name: workout-service
    app.kubernetes.io/part-of: fitforge
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: workout-service
  ports:
    - name: http
      port: 5003
      targetPort: 5003