apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: fitforge
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/part-of: fitforge
data:
  PORT: "5002"
  MONGO_URI: "mongodb://user_user:UserPass123@mongodb-headless.fitforge.svc.cluster.local:27017/user_db?replicaSet=rs0&authSource=user_db"