apiVersion: v1
kind: ConfigMap
metadata:
  name: progress-service-config
  namespace: fitforge
  labels:
    app.kubernetes.io/name: progress-service
    app.kubernetes.io/part-of: fitforge
data:
  PORT: "5005"
  MONGO_URI: "mongodb://progress_user:ProgPass123@mongodb-headless.fitforge.svc.cluster.local:27017/progress_db?replicaSet=rs0&authSource=progress_db"
  REDIS_HOST: "redis.fitforge.svc.cluster.local"
  REDIS_PORT: "6379"