apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  # namespace: default
  labels:
    app: mongo
spec:
  # Headless — required by StatefulSet for stable pod DNS
  clusterIP: None
  # This ensures DNS works even if the pod is "Not Ready"
  publishNotReadyAddresses: true
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
