architecture: replicaset
 
replicaCount: 3
 
replicaSetName: rs0
 
auth:

  enabled: true
 
  # Root credentials

  rootUser: root

  rootPassword: RootPass@123
 
  # Required for internal replica set communication

  replicaSetKey: RootPass@123
 
  # Application users (mapped 1:1)

  usernames:

    - auth_user

    - user_user

    - workout_user

    - nutrition_user

    - progress_user
 
  passwords:

    - AuthPass@3

    - UserPass@3

    - WorkPass@3

    - NutriPass@3

    - ProgPass@3
 
  databases:

    - auth_db

    - user_db

    - workout_db

    - nutrition_db

    - progress_db
 
persistence:

  enabled: true

  storageClass: local-path   # change if needed

  size: 5Gi
 
resources:

  requests:

    cpu: 250m

    memory: 256Mi

  limits:

    cpu: 900m

    memory: 1Gi
 
service:

  type: ClusterIP

  clusterIP: None   # Headless service (required for StatefulSet)
 